In [1]:
import numpy as np

In [4]:
#lets create array of 1's
arr_of_1=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(arr_of_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
#suppose if we have to 100*100 of 1's array the we cant do it manually thus we have function in python
arr=np.ones(100)
print(arr)
#data type check
arr.dtype

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


dtype('float64')

In [8]:
#suppose we have to make 3*4 array of 1
new_arr=np.ones((3,4))
print(new_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
#above matrix contains float type data if we want integer type data then
new_arr=np.ones((3,4),dtype=int)
print(new_arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
#similary if you want ot create element of zeros then you can 
arr_0s=np.zeros((3,4),dtype=int)
print(arr_0s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
#bool matrix
arr_bool=np.zeros((3,3),dtype=bool) #if we use np.zeros then it will create false matrix inplace of zeros put ones to create true matirx
print(arr_bool)

[[False False False]
 [False False False]
 [False False False]]


In [15]:
arr_bool=np.ones((3,3),dtype=bool)
print(arr_bool)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [17]:
arr_str=np.zeros((3,3),dtype=str)
print(arr_str)

[['' '' '']
 ['' '' '']
 ['' '' '']]


In [18]:
arr_str=np.ones((3,3),dtype=str)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [19]:
#lets create a empty matrix
arr_empty=np.empty((3,3))
print(arr_empty)  #it will print with garbage values

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.87341900e-321]
 [6.23057348e-307 1.42419530e-306 0.00000000e+000]]
