# numpy functions

In [5]:
import numpy as np;

# #arange()

In [6]:
a1=np.arange(10)  #syntax   np.arange(start,end,steps,dtype)  ,it will amke an 1d array of 0 to 9
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
#lets create array by gapping some elements as in function arguments steps have to pass there
even_ar=np.arange(0,10,2)
print(even_ar)

[0 2 4 6 8]


In [12]:
odd_ar=np.arange(1,10,2)
print(odd_ar)

[1 3 5 7 9]


# # linspace()

In [13]:
arr_linspace=np.linspace(0,100)
print(arr_linspace)

[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


## logspace ()

In [15]:
arr_logspace=np.logspace(0,20)
print(arr_logspace)

[1.00000000e+00 2.55954792e+00 6.55128557e+00 1.67683294e+01
 4.29193426e+01 1.09854114e+02 2.81176870e+02 7.19685673e+02
 1.84206997e+03 4.71486636e+03 1.20679264e+04 3.08884360e+04
 7.90604321e+04 2.02358965e+05 5.17947468e+05 1.32571137e+06
 3.39322177e+06 8.68511374e+06 2.22299648e+07 5.68986603e+07
 1.45634848e+08 3.72759372e+08 9.54095476e+08 2.44205309e+09
 6.25055193e+09 1.59985872e+10 4.09491506e+10 1.04811313e+11
 2.68269580e+11 6.86648845e+11 1.75751062e+12 4.49843267e+12
 1.15139540e+13 2.94705170e+13 7.54312006e+13 1.93069773e+14
 4.94171336e+14 1.26485522e+15 3.23745754e+15 8.28642773e+15
 2.12095089e+16 5.42867544e+16 1.38949549e+17 3.55648031e+17
 9.10298178e+17 2.32995181e+18 5.96362332e+18 1.52641797e+19
 3.90693994e+19 1.00000000e+20]


# #reshape()

In [35]:
a2=a1.reshape(5,2)  #rehaped 1d array in 2d array
print(a2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [27]:
a3=a2.reshape(5,2,1)
print(a3)

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]

 [[8]
  [9]]]


# # ravel()  it is used to create multidimensional array to 1D array

In [28]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# flatten()

In [34]:
print(a3.flatten('K'))  #use shift tab to check passing arguments

[0 1 2 3 4 5 6 7 8 9]


# transpose()

In [36]:
a2.transpose()

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [37]:
#or we can use array_name.T
a2.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [38]:
print(a2.T)

[[0 2 4 6 8]
 [1 3 5 7 9]]


# eye()

In [41]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])