# numpy concat and split

In [2]:
import numpy as np

In [7]:
a1=np.arange(1,17).reshape(4,4)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [5]:
a2=np.arange(17,33).reshape(4,4)
print(a2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [9]:
np.concatenate((a1,a2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [10]:
#concatenating rows
np.concatenate((a1,a2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [11]:
#vstack function is used to concatenate a1 and a2   (vertical)
np.vstack((a1,a2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [12]:
#hstack function is used to concatenate a1 and a2   (horizontal)
np.hstack((a1,a2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [13]:
np.hstack((a1,a2,a1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

# split()

In [21]:
list1=np.split(a1,2,axis=0)
print(list1)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [23]:
type(list1)

list

In [24]:
print(list1[0])

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
type(list1[0])   #when we use split array it will convert my array into list and that list contain type of arrray as you can see below

numpy.ndarray

In [26]:
list1=np.split(a1,2,axis=1)
print(list1)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


In [28]:
d1=np.arange(1,6)
print(d1)

[1 2 3 4 5]


In [32]:
np.split(d1,[1,3])

[array([1]), array([2, 3]), array([4, 5])]

In [33]:
print(np.split(d1,[1,3]))

[array([1]), array([2, 3]), array([4, 5])]
