# Mathematical operations as numpy

In [1]:
import numpy as np

In [8]:
a1=np.array([1,2,3,4])
a2=np.array([10,11,12,13])
print(a1+a2)  #addition of 2 arrays
print(a1-2)   #minus of 2 in every elemen



[11 13 15 17]
[-1  0  1  2]


In [9]:
a1+a2  #addition

array([11, 13, 15, 17])

In [10]:
np.add(a1,a2)  #addition using inbuilt function

array([11, 13, 15, 17])

In [12]:
a2-a1     #subtraction

array([9, 9, 9, 9])

In [13]:
np.subtract(a2,a1)   #subtraction using inbuilt function

array([9, 9, 9, 9])

In [23]:
arr1=np.arange(1,10).reshape(3,3)
print(arr1)
arr2=np.arange(1,10).reshape(3,3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [25]:
arr1*arr2  #it will multiply arr by element

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [26]:
#if you want to multiply array by row and column wise
arr1@arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [27]:
#division
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
#max element of array
print(arr1.max())
#index of maximum element in array
print(arr1.argmax())

9
8


In [34]:
arr1.max(axis=1)   #it will give maximu from axis 1

array([3, 6, 9])

In [ ]:
#similarly you can do it for find minimum element

In [36]:
#addition of every element in array
np.sum(arr1)

45

In [39]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [40]:
#avg of arrays we use mean function to find avg of array
np.mean(arr1)

5.0

In [41]:
np.mean(arr1+arr2)

10.0

In [42]:
#sqrt
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [43]:
#std deviation
np.std(arr1)

2.581988897471611

In [44]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [45]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [46]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])