# random()

In [2]:
import numpy as np
import random

In [3]:
np.random.random(10)

array([0.52708972, 0.21578205, 0.23477449, 0.46634562, 0.38320719,
       0.16638949, 0.99780878, 0.37809201, 0.88013279, 0.36967903])

In [4]:
print(np.random.random(1))

[0.91308751]


In [7]:
np.random.random((3,3))

array([[0.53351834, 0.1998754 , 0.89624919],
       [0.42575314, 0.56735039, 0.75960828],
       [0.46384024, 0.66578658, 0.98297755]])

In [9]:
np.random.randint(1,4)   #give us a random integer value with in the given range

2

In [12]:
np.random.randint(1,4,(4,4)) #creating 2d array using random

array([[3, 3, 3, 3],
       [1, 1, 2, 3],
       [2, 1, 3, 2],
       [2, 3, 1, 1]])

In [13]:
np.random.randint(1,4,(2,4,4))  # creating 3d array using random

array([[[3, 2, 3, 1],
        [2, 3, 2, 2],
        [3, 3, 2, 2],
        [1, 1, 1, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [2, 1, 2, 3],
        [3, 3, 3, 2]]])

In [16]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [17]:
x=[1,2,3,4]
np.random.choice(x)

2

In [18]:
for i in range(20):
    print(np.random.choice(x))

2
4
2
3
2
1
3
3
3
2
1
2
4
2
1
4
3
2
2
3


In [19]:
np.random.permutation(x)

array([2, 1, 3, 4])